openapi: 3.0.1
info:
  title: WorldBank
  version: 1.0.0
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /banks:
    get:
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
    post:
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
  /banks/{bankId}:
    get:
      parameters:
       -
        name: bankId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
